### ISSUE TITLE
Menu doesn't open sometimes? 1.7.10

### ISSUE THREAD

**Issue by ThatPolishKid99** [GotoLink/LevelUp#7]
Whenever I load up a world. survival or creative, I haven't been able to get it to open the menu...I open it consistently on a survival world that I have been working on for ever, and is well established. But any other world? nada

**Comment by GotoLink** [comment]
Config values ? Player xp ?
Survival/creative doesn't matter.

**Comment by ThatPolishKid99** [comment]
Im a dummy, whoops... It works, im just stupid
